version: '3.8'

services:
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-east-1
      - GRAPHQL_URL=http://graphql-service:4000/graphql
      - SQS_QUEUE_URL=http://sqs-service:9324/queue/notification-queue
    secrets:
      - aws_credentials
      - notification_db_credentials
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  graphql-service:
    image: graphql-service-image
    container_name: graphql-service
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    depends_on:
      - postgres

  sqs-service:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510:4510"
    environment:
      - SERVICES=sqs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres-data:

secrets:
  aws_credentials:
    external: true
  notification_db_credentials:
    external: true
