// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	ID        string `json:"id"`
	ProductID string `json:"productId"`
	Quantity  int32  `json:"quantity"`
	Status    string `json:"status"`
}

type Query struct {
}
