# nginx/nginx.conf
events {
    worker_connections 1000;
}

http {
    upstream backend_servers {
        # Defaults to round-robin
        server server-app-1:4000;
        server server-app-2:3000;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # other proxy settings
        }
    }
}
