services:
  orders-service:
    build:
      context: ./backend/order-service
    ports:
      - '9001:9001'
    env_file:
      - ./backend/order-service/.env
    dns:
      - 10.0.2.20
    environment:
      - PORT=9001
      - DATABASE_URL=orders-db:5432
      - AWS_ENDPOINT=http://localstack:4566
    depends_on:
      - orders-db
      - localstack
    networks:
      - app-network
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - EDGE_PORT=4566
      - SERVICES=sqs,events
    ports:
      - '4566:4566'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
