services:
  # orders-service:
  #   build:
  #     context: .
  #   ports:
  #     - '9001:9001'
  #   env_file:
  #     - .env
  #   dns:
  #     - 10.0.2.20
  #   environment:
  #     - PORT=9001
  #     - DATABASE_URL=orders-db:5432
  #     - AWS_ENDPOINT=http://localstack:4566
  #   depends_on:
  #     - orders-db
  #     - localstack
  #   # networks:
  #   #   - app-network
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - EDGE_PORT=4566
      - SERVICES=sqs,events
    ports:
      - '4566:4566'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    # networks:
    #   - app-network
  orders-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - '5431:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - app-network
volumes:
  postgres_data:
# networks:
#   app-network:
