name: On issue created

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  issue_created:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.5'

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./... > gosec_report.txt || true

      - name: Upload gosec report
        uses: actions/upload-artifact@v4
        with:
          name: gosec-report