name: On issue created

permissions:
  contents: write
  issues: write

on:
  issues:
    types: [opened]

jobs:
  issue_created:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const issueComment = "Thank you for opening this issue! We will look into it soon.";
            const issueNumber = context.issue.number;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: issueComment,
            });

            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Bugs']
            })
