on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      pnpm_version:
        required: false
        type: string
        default: 9.4.0
      go_version:
        required: false
        type: string
        default: 1.24.5
    secrets:
      sonar_token:
        required: true
      npm_token:
        required: true

permissions:
  id-token: write
  contents: read
  actions: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
  sonar:
    runs-on: ubuntu-latest
    needs: gosec
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-golang-project \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
  golangci:
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: run --timeout 5m
          version: v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOLANGCI_LINT_CACHE_DIR: ${{ github.workspace }}/.cache/golangci-lint
