on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      pnpm_version:
        required: false
        type: string
        default: 9.4.0
      node_version:
        required: false
        type: string
        default: 20.x
    secrets:
      sonar_token:
        required: true
      npm_token:
        required: true

permissions:
  id-token: write
  contents: read
  actions: read
  issues: read
  checks: write
  pull-requests: write

env:
  SONAR_TOKEN: ${{ secrets.sonar_token }}
  NPM_TOKEN: ${{ secrets.npm_token }}

jobs:
  unit_test:
    name: Unit Tests - ${{ inputs.project_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm ${{ inputs.pnpm_version }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm_version }}
      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - name: Add NPM token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
      - name: Install Dependencies
        run: pnpm install --shamefully-hoist=true
      - name: Run Unit Tests
        run: pnpm test:ci
        working-directory: ./apps/${{ inputs.project_name }}
      - name: SonarQube Scan Of Unit Test - ${{ inputs.project_name }}
        if: success() || failure()
        continue-on-error: true
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        with:
          projectBaseDir: ./apps/${{ inputs.project_name }}
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          SONAR_HOST_URL: https://sonarcloud.io/
          RUNNER_DEBUG: 1
