on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      pnpm_version:
        required: false
        type: string
        default: 9.4.0
      go_version:
        required: false
        type: string
        default: 1.24.5
    secrets:
      sonar_token:
        required: true
      npm_token:
        required: true

permissions:
  id-token: write
  contents: read
  actions: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.5'

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./... > gosec_report.txt || true

      - name: Upload gosec report
        uses: actions/upload-artifact@v4
        with:
          name: gosec-report
          path: gosec_report.txt
  sonar:
    runs-on: ubuntu-latest
    needs: gosec
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-golang-project \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
